name: dance-at-snowmass
channels:
  - conda-forge
dependencies:
  - pip
  - python
  - xrootd
  - pip:
    - awkward>=1.5
    - matplotlib>=3.4
    - numpy
    - uproot>=4.1
    - vector>=0.8.2
    - mplhep
    - hist
    - uproot-browser
